### ISSUE TITLE
"String was not recognized as a valid DateTime."

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/HealthChecker#11]
Exception calling "Parse" with "1" argument(s): "String was not recognized as a valid DateTime."
At line:6 char:21
+                     [DateTime]::Parse($this.psBase.properties["InstalledOn"].Val ...
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FormatException
 

This issue only occurs on none English systems it seems.

**Comment by EC-WTW** [comment]
Do you mean non-US English machines?
I get this same message logged repeatedly on my en-GB (2057) machines, my en-US (1033) machines are fine.
Great script, very helpful.
Thanks

**Comment by dpaulson45** [comment]
@EC-WTW, I actually wasn't aware that this issue only occurred for en-US. If you can reproduce the issue in en-GB then that would make testing a little 'easier' because I can create a VM with that language and not struggle with trying to translate some things. Thanks for providing your feedback.

**Comment by Apoc70** [comment]
I don't see issues on a de-DE machine.

**Comment by dpaulson45** [comment]
So I am not sure what is fully causing it, but it is in the cmdlet Export-Clixml. My guess is that it isn't in the format that it expects because likely a Time Format Change, so we error out here. I ended up just moving the Export-Clixml cmdlet to after the check for errors, because it is a silent error, we wont see it anyways. This has been checked in.
