### ISSUE TITLE
Error handling for WMI Win32_PowerPlan

### ISSUE THREAD

**Issue by Apoc70** [dpaulson45/HealthChecker#12]
When executing the script in a hardened infrastructure, the Get-WmiObject -Class Win32_PowerPlan fails.
The $plan variable is $null which results in the error message "High Performance Power PLan is recommended"

Handling a $plan = $null situation would be an enhancement of the script outout.

`
try { 
      $plan = Get-WmiObject -ComputerName $Machine_Name -Class Win32_PowerPlan -Namespace root\cimv2\power -Filter "isActive='true'" 
    }
    catch {
      $plan = $null
    } 
`

`
if($plan -ne $null) { 
      if($plan.InstanceID -eq "Microsoft:PowerPlan\{8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c}")
      {
          Write-VerboseOutput("High Performance Power Plan is set to true")
          $os_obj.HighPerformanceSet = $true
      }
      $os_obj.PowerPlanSetting = $plan.ElementName
      $os_obj.PowerPlan = $plan 
    }
    else {
      Write-VerboseOutput('Power Plan information could not be read')
      $os_obj.HighPerformanceSet = $false
      $os_obj.PowerPlanSetting = 'N/A'
      $os_obj.PowerPlan = $plan
    } 
`

`
    Write-Grey("Power Settings:")
    if($HealthExSvrObj.OSVersion.HighPerformanceSet)
    {
        Write-Green("'tPower Plan: " + $HealthExSvrObj.OSVersion.PowerPlanSetting)
    }
    elseif($HealthExSvrObj.OSVersion.PowerPlan -eq $null) { 
      Write-Red("'tPower Plan not accessible")
    }
    else
    {
        Write-Red("'tPower Plan: " + $HealthExSvrObj.OSVersion.PowerPlanSetting + " --- Error: High Performance Power Plan is recommended")
    } 
`

**Comment by dpaulson45** [comment]
Completed - v2.7
