### ISSUE TITLE
Vulnerability check by buildrevision is not working properly 

### ISSUE THREAD

**Issue by lusassl-msft** [dpaulson45/HealthChecker#130]
We have to investigate why this is not working properly. 
This should be the problematic line:

[double]$buildRevision = [System.Convert]::ToDouble(("{0}.{1}" -f $HealthExSvrObj.ExchangeInformation.ExchangeSetup.FileBuildPart, $HealthExSvrObj.ExchangeInformation.ExchangeSetup.FilePrivatePart))

**Comment by dpaulson45** [comment]
This is interesting. I would think there is a better way to do this than switching the Culture on the thread. When trying out your repro script I am not able to get this to work, but in theory, it should be the same results as what you are trying to do. 

ToDouble(Object, IFormatProvider)
https://docs.microsoft.com/en-us/dotnet/api/system.convert.todouble?view=netframework-4.7.2

[System.Convert]::ToDouble(123.45, [System.Globalization.CultureInfo]::new("en-US"))

Works just fine within my normal PowerShell, but within the script when I have switched the CurrentCulture it fails to work properly.

**Comment by dpaulson45** [comment]
@lusassl-msft  much better option. Thanks for looking into this.

**Comment by lusassl-msft** [comment]
Fixed in v2.32
