### ISSUE TITLE
Add digital signature (Authenticode) to HealthChecker release

### ISSUE THREAD

**Issue by lusassl-msft** [dpaulson45/HealthChecker#133]
We should think about adding a digital authenticode signature to Health Checker before releasing a new version (https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-authenticodesignature?view=powershell-6). Some users are not able to run scripts from the internet if they are not signed (ExecutionPolicy RemoteSigned or AllSigned).

**Comment by dpaulson45** [comment]
This would be hard to do as the cert would need to be provided by a 3rd party vs just one you created. Do have many customers that run into this issue? I mean we do have multiple scripts that we commonly use that aren't signed that we use to troubleshoot.

**Comment by lusassl-msft** [comment]
Yes, there are some customers which are enforced to only run signed scripts if they are downloaded from the internet. I'll check possibilities to get 3rd party code signing certificate.

**Comment by lusassl-msft** [comment]
We're thinking about to provide a hash (SHA256) of each new release on the site. So everyone can validate that the downloaded version is the same as the version we provide here on GitHub. So you can make sure that the script wasn't manipulated (for example on transport). This is important because the script must run on administrative context.

**Comment by lusassl-msft** [comment]
Hash information are listed here and will be updated for each new release: https://github.com/dpaulson45/HealthChecker/releases
