### ISSUE TITLE
Improve CAS Load Balancing Report feature

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/HealthChecker#147]
Currently, the script is going through each counter one by one vs doing it in bulk which can make it faster. Should really update this as well as include addition verbose information.

**Comment by dpaulson45** [comment]
So what we are currently doing is the following: 

`
foreach($cas in $CASServers)
    {
        #Total connections
        $TotalConnectionCount = (Get-Counter ("\\" + $cas.Name + "\Web Service(Default Web Site)\Current Connections")).CounterSamples.CookedValue
        $CASConnectionStats.Add($cas.Name, $TotalConnectionCount)
        $TotalCASConnectionCount += $TotalConnectionCount

        #AutoD requests
        $AutoDRequestCount = (Get-Counter ("\\" + $cas.Name + "\ASP.NET Apps v4.0.30319(_LM_W3SVC_1_ROOT_Autodiscover)\Requests Executing")).CounterSamples.CookedValue
        $AutoDStats.Add($cas.Name, $AutoDRequestCount)
        $TotalAutoDRequests += $AutoDRequestCount
..... so on
`

This isn't ideal it is extremely slow and we aren't taking full advantage of Get-Counter. I would be nice to fully utilize the Get-Counter command and do the following: 

`Get-Counter -Computer "Server1","Server2","Server3" -Counter "\ASP.NET Applications(_LM_W3SVC_1_ROOT_Rpc)\Requests Executing","\ASP.NET Applications(_LM_W3SVC_1_ROOT_ECP)\Requests Executing"...(for all the counters - could also do a wild card for all instances and only look at the ones we want)
`
From here we pull out the data and look at it how we would like. 

@lusassl-msft  would you like to work on this?

**Comment by lusassl-msft** [comment]
@dpaulson45  yep, please assign to me. Thank you!

**Comment by dpaulson45** [comment]
Checked into Dev3.0
