### ISSUE TITLE
KB3206632 included in new CUs

### ISSUE THREAD

**Issue by amrvan** [dpaulson45/HealthChecker#153]
Hi,
After installing Exchange server 2016 CU12 on Windows 2016 with latest April CU (April 25, 2019—KB4493473), script throw a false positive.

**Comment by lusassl-msft** [comment]
Will check this

**Comment by lusassl-msft** [comment]
@amrvan I'm unable to reproduce this. Please run HealthChecker with -verbose switch and send me the report to lusassl@microsoft.com.
Thank you!

**Comment by amrvan** [comment]
Hi Lukas,
I think it's because script seems to be checking "clusport.sys" file, but this file does not exist on Windows 2016 with latest April CU (April 25, 2019—KB4493473). If it will be necessary i can send the file (containing edited information that can be sensitive). 
Thanks

**Comment by lusassl-msft** [comment]
clusport.sys should still be there but its file version has been changed from 10.0.14393.**576** to 10.0.14393.**2938**. I'll keep you posted. Thank you.

**Comment by lusassl-msft** [comment]
@amrvan we check if FileMajorPart, FileMinorPart, FileBuildPart and FilePrivatePart are equal or greater than expected and if so the check will passed. As mentioned before, KB4493473 includes clusport.sys which is greater than the one brought to us by KB3206632 (find the file information for cumulative update 4493473 here: http://download.microsoft.com/download/8/D/A/8DAF9D03-D5CB-450C-BAF6-A2952F03444D/4493473.csv). So please download the latest version, change line 3429 from: 
Get-BuildLevelVersionCheck -ActualVersionObject $ServerBuild -CheckVersionObject $CheckVersion -**DebugFunction $false**
to: 
Get-BuildLevelVersionCheck -ActualVersionObject $ServerBuild -CheckVersionObject $CheckVersion -**DebugFunction $true**
 and run the script with -verbose switch. 

Thank you!

**Comment by dpaulson45** [comment]
@amrvan are you able to follow the steps that lusassl-msft provided so we can determine why this issue might be occurring in your environment?

**Comment by dpaulson45** [comment]
looks like this can be caused by the server not being in a DAG and not having the clusport.sys driver. I would assume this can happen on the edge server as well, so would need to look into this again and see what files change that we can test against.

**Comment by dpaulson45** [comment]
@lusassl-msft can you check to see if this is resolved when you don't have a server in a DAG.

**Comment by lusassl-msft** [comment]
Will run the check soon and keep you posted

**Comment by lusassl-msft** [comment]
First test on Exchange 2016 CU12 on Server 2016. Still get this warning.

Hotfix KB3206632 is recommended for this OS and was not detected.  Please consider installing it to prevent performance issues. --- Note that this KB update may be superseded by another KB update. To verify, check the file versions in the KB against your machine. This is a temporary workaround till the script gets properly updated for all KB checks.

There is no clusport.sys available to check.

**Comment by dpaulson45** [comment]
removing KB checks in Dev3.0.0
