### ISSUE TITLE
Add the ability to pass a Server List and execute the script on each server at once

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/HealthChecker#158]
Need to add a parameter called -Servers that would be able to execute the script on each server in the list all at once. This would allow the script to complete quicker. In order for this to work, need the following done. 

-Update Write-Host information for the remote execution to be done in a smarter way. 
-Write out a debug script log, no longer need to do -Verbose to have debug information. 
-Return our HealthChecker object back to the main execution 
-Analyze the results on the main execution session and display the results in an HTML view as well as writing out all the data to text file the same as before.

**Comment by lusassl-msft** [comment]
I'd recommend to make the -server parameter multi-server capable instead of adding another parameter.

**Comment by worldsdream** [comment]
Just my two cents:

It would be best to have two options:
1: Add mulitple servers, we can choose what we want. For example -Server EX01,EX02,EX04
2: Add all servers at once
