### ISSUE TITLE
Write out a debug log

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/HealthChecker#160]
Either always write out a debug log, or store all the values that we are looking for in a variable and if something major occurs write it out.

**Comment by dpaulson45** [comment]
Look into Start-Transcript and Stop-Transcript to see if this what we are looking for. Place inside of a Try Finally block to always do a cleanup if required at the end of the script. 

@lusassl-msft will look into this.

**Comment by lusassl-msft** [comment]
Do we want to store the debug log in parallel or should we replace the "default" .txt output file?

**Comment by dpaulson45** [comment]
We would want to do it in parallel. 

The debug will always include the default information. The default will only include the debug if we display it on screen with -Verbose. 

Then we delete the debug log if no errors were detected or when we have the Verbose switch set.
