### ISSUE TITLE
Include Exchange June Quarterly Release 2019

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/HealthChecker#193]
Our Quarterly release should be coming out sometime soon this month. We are holding off on the next release till this is complete. 

@lusassl-msft will be updating the script for this once the release has been made.

**Comment by dpaulson45** [comment]
@lusassl-msft looks like it was released today. 

https://techcommunity.microsoft.com/t5/Exchange-Team-Blog/Released-June-2019-Quarterly-Exchange-Updates/ba-p/698398

**Comment by lusassl-msft** [comment]
Yep, will implement it tomorrow :-)
