### ISSUE TITLE
Visual C++ 2013 Checker Incorrect

### ISSUE THREAD

**Issue by damianscoles** [dpaulson45/HealthChecker#200]
I was testing your script to validate some work I am doing with Exchange scripts when I noticed that Visual C++ 2013 was showing as out of date.   This result was despite the fact that I had just downloaded the latest version from Microsoft.  I did some digging into what version you were looking for and what version I had when I noticed that my version was newer than your requirement.   Yet the script was reporting it as out of date.  In the script, the current version is listed as '201367252' and the version I have installed on my server is '201367256'.  Is there a way you can modify the script to see if the installed version is later as well?  The outdated result was throwing me.  Thanks.

**Comment by lusassl-msft** [comment]
Hi @damianscoles . This issue will be fixed with v2.34 which will be released soon.

**Comment by dpaulson45** [comment]
@damianscoles  this is now released.
