### ISSUE TITLE
TLS check not successful

### ISSUE THREAD

**Issue by Maeffy** [dpaulson45/HealthChecker#220]
I found an issue with the values read from this keys (valid for all keys TLS 1.0, TLS 1.1, TLS 1.2,...)

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server]
"Enabled"=dword:ffffffff

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client]
"Enabled"=dword:ffffffff

If IIS Crypto Tool from Nartac Software is used and "Best Practices" are loaded the Enabled DWORD will be set to 0xffffffff which is "-1" in the query. Seams to be a valid Value but the script only checks for "0" and "1". Would it be possible to also check for the "-1" value ?

Current Version healtchecker tried:  2.36.1
Current Version IIS Crypto: 3.0 Build 14

Best regards,
Manfred

**Comment by lusassl-msft** [comment]
Thanks for reporting that issue @Maeffy . We'll check that and come back to you if we've more questions.

**Comment by dpaulson45** [comment]
@Maeffy Is setting the Enabled registry key to a value of -1 going to enable or disable the TLS setting? 

We will need to check this to understand if this or any other value other than 0 disables the key.

**Comment by lusassl-msft** [comment]
As discussed internally:
It seems that we check if _Enabled_ REG_DWORD exists and has a value other than 0.
For example: If I create this REG_DWORD with a value of 12345, I'm able to connect using openssl:

openssl.exe s_client -connect 192.168.0.3:443 -tls1
<snip>
SSL handshake has read 2174 bytes and written 236 bytes
Verification error: unable to verify the first certificate
---
New, TLSv1.0, Cipher is ECDHE-RSA-AES256-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1
    Cipher    : ECDHE-RSA-AES256-SHA
    Session-ID: 8E3D000078B7DF59D865721116A4E097EB039FC699AB306DAFBCA108CD730D92
<snip>

I think that's the reason why TLS is working even if Enabled REG_DWORD is 0xffffffff.
All our documentations are about using 1 or 0 to control these settings (https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings#tls-12).
AFAIK the 0xffffffff value is use to control the cipher algorithms as documented here (https://support.microsoft.com/en-us/help/245030/how-to-restrict-the-use-of-certain-cryptographic-algorithms-and-protoc)

**Comment by dpaulson45** [comment]
Will need to update the code to detect anything other than 1 or 0 and provide a link to our documentation provide that it should be set with a 1 or a 0 and nothing else.

**Comment by dpaulson45** [comment]
If we still want to do this, we would need to update `Get-AllTlsSettingsFromRegistry` to record the value key. It would also be a lot of additional logic in the `Start-AnalyzerEngine` to determine this fact as well.

Not sure if this is going to be worth the time to update the script for this where i see little value add when we only support a 0 or 1.

@lusassl-msft what are your thoughts?

**Comment by lusassl-msft** [comment]
As discussed internally: We should validate if any other value than 0 or 1. If this is the case, we should display a warning that the configuration is incorrect and may lead to misbehavior.

**Comment by Maeffy** [comment]
Hi

Thanks for your effort to clearify this.
Seems Nartac changed their tool to address this issue. The current version has implemented an override:

Version 3.2 Build 16 - Released April 11, 2020
  Added override enabled feature to set Procotols Enabled to 1 instead of 0xffffffff

Looks like you both did a great job to solve this.
I apprechiate your work on this.

Thanks and best regards,
Maeffy

**Comment by Karl-WE** [comment]
@dpaulson45 I did expierence the same. [Nartac IIS Crypto](https://www.nartac.com/Products/IISCrypto)will use Enabled:0xffffffff instead of 0x00000001. Technically both means the same (enabled). It would be great if your check will treat both values as "True".
