### ISSUE TITLE
Hyperthreading status not displayed correctly in html report

### ISSUE THREAD

**Issue by bartmgithub** [dpaulson45/HealthChecker#221]
Cmdline mode reports hyperthreading enabled for a server, but html report shows disabled. HTML does show 12 physical and 24 logical in server details.

**Comment by bartmgithub** [comment]
this is Exchange 2013 CU23 on Windows 2012 R2 with latest healthchecker.ps1

**Comment by dpaulson45** [comment]
@bartmgithub can you provide the xml output from one of your servers me? Please email the results to ExToolsFeedback@microsoft.com so i am able to view this.

**Comment by bartmgithub** [comment]
I’m no longer onsite, but might be able to get this next week.
Not sure if they will allow as normally they do not want to provide any logs externally.

**Comment by dpaulson45** [comment]
@bartmgithub i should have this fixed actually now in the next release of the script.
