### ISSUE TITLE
Errors and script doesn't execute correctly

### ISSUE THREAD

**Issue by mpkumar82** [dpaulson45/HealthChecker#223]
At C:\Users\pavanmaganti\Desktop\HealthChecker.ps1:143 char:19
+               Sign&nbsp;up
+                   ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\Users\pavanmaganti\Desktop\HealthChecker.ps1:170 char:190
+ ... ures">Features <span class="Bump-link-symbol float-right text-normal text-gray-l ...
+                    ~
The '<' operator is reserved for future use.
At C:\Users\pavanmaganti\Desktop\HealthChecker.ps1:170 char:261
+ ... xt-gray-light">&rarr;</span></a>
+                    ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\Users\pavanmaganti\Desktop\HealthChecker.ps1:184 char:255
+ ... stomer stories <span class="Bump-link-symbol float-right text-normal text-gray-l ...
+                    ~
The '<' operator is reserved for future use.
At C:\Users\pavanmaganti\Desktop\HealthChecker.ps1:184 char:326
+ ... xt-gray-light">&rarr;</span></a></li>
+                    ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\Users\pavanmaganti\Desktop\HealthChecker.ps1:185 char:231
+ ... rity">Security <span class="Bump-link-symbol float-right text-normal text-gray-l ...
+                    ~
The '<' operator is reserved for future use.
At C:\Users\pavanmaganti\Desktop\HealthChecker.ps1:185 char:302
+ ... xt-gray-light">&rarr;</span></a></li>
+                    ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\Users\pavanmaganti\Desktop\HealthChecker.ps1:205 char:222
+ ... Explore GitHub <span class="Bump-link-symbol float-right text-normal text-gray-l ...
+                    ~
The '<' operator is reserved for future use.
At C:\Users\pavanmaganti\Desktop\HealthChecker.ps1:205 char:293
+ ... xt-gray-light">&rarr;</span></a></li>
+                    ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\Users\pavanmaganti\Desktop\HealthChecker.ps1:208 char:107
+ ... pt-lg-3">Learn &amp; contribute</h4>
+                    ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : AmpersandNotAllowed

**Comment by dpaulson45** [comment]
@mpkumar82 it would appear that you copied the script from the site not downloaded it. Please correctly download the script from the Releases tab, as none of the errors that are provided within the above text is actually within the script.

**Comment by dpaulson45** [comment]
@mpkumar82, please let me know if you are still running into this issue. Otherwise, i will proceed to close out this issue.

**Comment by dpaulson45** [comment]
Closing out issue due to inactivity. Also doesn't appear to be an actual issue as the script doesn't appeared to have been downloaded correctly from the Releases page.
