### ISSUE TITLE
Remote management network adapater

### ISSUE THREAD

**Issue by smwk** [dpaulson45/HealthChecker#230]
On a Dell system the script is picking up the iDrac network adapter:

```
NIC settings per active adapter:
        Interface Description: Remote NDIS Compatible Device [Ethernet]
                Warning: NIC driver is over 1 year old. Verify you are at the latest version.
                Driver Date: 06/21/2006 00:00:00
                Driver Version: 10.0.14393.0
                Link Speed: 425.984 Mbps
                MTU Size: 1500
                RSS: No RSS Feature Detected.
                IPv6Enabled: True
                Packets Received Discarded: 0
```

Can this be excluded?

**Comment by smwk** [comment]
I've sent on the XML file now.

**Comment by dpaulson45** [comment]
@smwk  is it possible that the name could be different on different OSs? 

I found this article, and it looks like on Windows 2016 OS the name of the NIC appears to be a standard that I could exclude, however, I would like to make sure that it would also do it for Windows 2019 for sure as well as older OSs. 

https://www.dell.com/support/manuals/us/en/04/idrac-service-module-v3.0.1/ism_3.0.1_users_guide/installing-the-idrac-service-module-on-microsoft-windows-operating-systems?guid=guid-ecb11c9e-dfbc-4b45-ab0c-4ce7f718bf96&lang=en-us

**Comment by smwk** [comment]
It might be but unfortunately I have no way of checking as we only have Server 2016 deployed at work.
