### ISSUE TITLE
System path check

### ISSUE THREAD

**Issue by smwk** [dpaulson45/HealthChecker#231]
This might be beyond the scope of the script but recently I had an issue updating Broadcom network drivers. It turned out the issue was with system path which started with 2 semi-colons:

`; ;%SystemRoot%\system32;...`

As soon as they were removed I could update the Nic driver. It would be handy to have the script detect this.

**Comment by dpaulson45** [comment]
This might be outside of the scope of the script. Were you able to see this within $env:path?

**Comment by smwk** [comment]
I tested there and yes it can be seen with $env:path .

**Comment by dpaulson45** [comment]
Closing out as it is outside of the scope of the script.
