### ISSUE TITLE
Update Loading Exchange Management Snapin 

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/HealthChecker#238]
To be more secure and in the supported recommend way to connect to an Exchange Management Shell, update the script to load in the session with New-PSSession while asking for credentials. Need to make sure we handle the failure to properly provide credentials to avoid any additional issues with the script. 

https://docs.microsoft.com/en-us/powershell/exchange/exchange-server/connect-to-exchange-servers-using-remote-powershell?view=exchange-ps

**Comment by lusassl-msft** [comment]
I can take care of this one. Please assign if I should do.
Thanks

**Comment by lusassl-msft** [comment]
As discussed we're planning to address it correctly in Dev3.0.0

**Comment by dpaulson45** [comment]
Ended up Cherry Picking this into Dev2.38.0 fe71a295fdd6ebd63828b8937d72342e09324ded
