### ISSUE TITLE
OS detection does not work properly on Windows Server 2019

### ISSUE THREAD

**Issue by lusassl-msft** [dpaulson45/HealthChecker#252]
This is because we change the build number with every larger Windows 10 / Server 2019 update like 19H2, 20H1 etc.

**Comment by dpaulson45** [comment]
For the Dev2.* branch, let's just put in a catch for if it isn't 2016 version build, but starts with 10.0 for the string, let's just place it as Windows Server 2019. 

For Dev3.0.0 branch, let's look at using the property Caption on the Win32_OperatingSystem WmiObject class for all the server versions. Let's return a string for the MajorVersion type that it is.
