### ISSUE TITLE
Include additional information for installed updates

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/HealthChecker#260]
https://superuser.com/questions/1002015/why-are-get-hotfix-and-wmic-qfe-list-in-powershell-missing-installed-updates

**Comment by lusassl-msft** [comment]
I think commit #73b107b may do the job

**Comment by dpaulson45** [comment]
> I think commit #73b107b may do the job.
> [73b107b](https://github.com/dpaulson45/HealthChecker/commit/73b107b55135fe0e64ba88ac0498a84a45c21900)

I will have to look into that. I am completely changing the way we currently have the classes within the script. I am going be storing all of this within the object.

**Comment by dpaulson45** [comment]
No longer going to do this as we don't look for any updates. We removed all that code in v3.0.0
