### ISSUE TITLE
Change OS Major Version Detection Dev3.0.0 Branch

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/HealthChecker#269]
With Windows Server 2019, we change the build number often. Need to change how we detect the Major Version that we are on. Look at using the property Caption on the Win32_OperatingSystem WmiObject class for all the server versions. Let's return a string for the MajorVersion type that it is.

From issue #252

**Comment by lusassl-msft** [comment]
We may also get the product version by checking Kernel32.dll:

`(Get-Item $env:windir\system32\kernel32.dll).VersionInfo`

`(Get-Item $env:windir\system32\kernel32.dll).VersionInfo.FileBuildPart`

**Comment by dpaulson45** [comment]
@lusassl-msft what does your Windows Server 2019 show for that? I would assume that the kernel32.dll would still change with the Updates

**Comment by lusassl-msft** [comment]
```
PS C:\windows\system32> (Get-Item $env:windir\system32\kernel32.dll).VersionInfo | fl *


FileVersionRaw     : 10.0.17763.1158
ProductVersionRaw  : 10.0.17763.1158
Comments           :
CompanyName        : Microsoft Corporation
FileBuildPart      : 17763
FileDescription    : Windows NT BASE API Client DLL
FileMajorPart      : 10
FileMinorPart      : 0
FileName           : C:\windows\system32\kernel32.dll
FilePrivatePart    : 1158
FileVersion        : 10.0.17763.771 (WinBuild.160101.0800)
InternalName       : kernel32
IsDebug            : False
IsPatched          : False
IsPrivateBuild     : False
IsPreRelease       : False
IsSpecialBuild     : False
Language           : English (United States)
LegalCopyright     : © Microsoft Corporation. All rights reserved.
LegalTrademarks    :
OriginalFilename   : kernel32
PrivateBuild       :
ProductBuildPart   : 17763
ProductMajorPart   : 10
ProductMinorPart   : 0
ProductName        : Microsoft® Windows® Operating System
ProductPrivatePart : 1158
ProductVersion     : 10.0.17763.771
SpecialBuild       :
```

![image](https://user-images.githubusercontent.com/40993616/87450549-ebffdb00-c5fe-11ea-8504-9fe7c8f1ef68.png)

**Comment by dpaulson45** [comment]
I feel like that is going to follow the WMI object, so we would still be in the same boat. We can do the great than option for the time being, but would need to be addressed once the next Window Server version comes out.

**Comment by lusassl-msft** [comment]
Okay, stumbled over it and thought it would be helpful
