### ISSUE TITLE
Confirm-ExchangeShell doesn't work on Edge servers

### ISSUE THREAD

**Issue by lusassl-msft** [dpaulson45/HealthChecker#272]
The Confirm-ExchangeShell doesn't work on Exchange Edge servers.
Problem is that we cannot load the RemoteExchange.ps1 because it's not there.
We need to do it this way to stay supported:
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -PSConsoleFile "C:\Program Files\Microsoft\Exchange Server\V15\bin\exshell.psc1" -noexit -command ". 'C:\Program Files\Microsoft\Exchange Server\V15\bin\Exchange.ps1'"

This has been validated on Exchange 2016 Edge server. I'll check what the best way is to solve this issue.

**Comment by dpaulson45** [comment]
Let's look and see if there is a registry to detect an Edge Server, or something like that.

Then provide that you must lunch EMS and run the script.

**Comment by lusassl-msft** [comment]
I think we can do it better:
1. Read exshell.psc1, it looks like this:
<?xml version="1.0" encoding="utf-8"?>
<PSConsoleFile ConsoleSchemaVersion="1.0">
  <PSVersion>1.0</PSVersion>
  <PSSnapIns>
    <PSSnapIn Name="Microsoft.Exchange.Management.PowerShell.E2010" />
  </PSSnapIns>
</PSConsoleFile>

2. ForEach SnapIn in PSSnapIns do Add-PSsnapin <SnapinName>
3. Import-Module C:\Program Files\Microsoft\Exchange Server\V15\bin\Exchange.ps1

Should do the job well.

**Comment by lusassl-msft** [comment]
We may check for HKLM:\SOFTWARE\Microsoft\ExchangeServer\v15\EdgeTransportRole to determine if we're on Edge Transport Server
