### ISSUE TITLE
Improve Vulnerability Checks Dev3.0.0

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/HealthChecker#284]
There should be a way to reduce the amount of code that we have here. Might be able to pass an array of Build Numbers as well as CVENames to the Get-VulnerabilitiesByBuildNumbersForDisplay

**Comment by lusassl-msft** [comment]
I'll take care of this. Please assign to me.

**Comment by dpaulson45** [comment]
We are going to be handling this in the Dev3.0.0 branch in this commit: b9fed60086dfbb2629bcc7f5b7d0ccdf892f2c96
