### ISSUE TITLE
Optimize SMB1 check for Server 2012 R2 or greater

### ISSUE THREAD

**Issue by lusassl-msft** [dpaulson45/HealthChecker#286]
I have received feedback that it confuses customers when we show the red error message if FS-SMB1 Windows Feature is disabled but Set-SmbServerConfiguration -EnableSMB1Protocol is set to true on Server 2012 R2 or greater. 
EnableSMB1Protocol to false is kind of failsafe to make sure that SMB1 is blocked even if Install-WindowsFeature -Name FS-SMB1 is executed to add SMB1 protocol support again.

We should optimize the logic here:
WindowsFeature false and SmbServerConfiguration false --> very good = green
WindowsFeature false and SmbServerConfiguration true --> good but can be improved = yellow
WindowsFeature true and SmbServerConfiguration false --> okay but can be much better = yellow
WindowsFeature true and SmbServerConfiguration true --> very bad = red

**Comment by dpaulson45** [comment]
added in 831e634b240d569b36d1bde93a31511c870a8b34
