### ISSUE TITLE
Check to see if Credential Guard is enabled on server

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/HealthChecker#303]
If credential guard is on the server, provide that we don't support it. 

Check for the best option to see if it is on the Exchange server. Process: LsaIso.exe

**Comment by lusassl-msft** [comment]
We may also check if the LsaCfgFlags DWORD exists as described here: https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage

```Enable Windows Defender Credential Guard:

Go to HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\LSA.
Add a new DWORD value named LsaCfgFlags. Set the value of this registry setting to 1 to enable Windows Defender Credential Guard with UEFI lock, set it to 2 to enable Windows Defender Credential Guard without lock, and set it to 0 to disable it.```
