### ISSUE TITLE
The WinRM Client Received an HTTP Status code of 403 when get remote information when using Invoke-Command

### ISSUE THREAD

**Issue by JCothern** [dpaulson45/HealthChecker#308]
When running the healthchecker against a remote server in some environments that use proxyservers may cause invoke-Command execution to return a 403 error.  

I found this article https://community.idera.com/database-tools/powershell/powertips/b/tips/posts/powershell-remoting-and-http-403-error

I did some testing by changing some of the code to test that and it resolved the issue for that area.  But there are many areas within the code that uses Invoke-command.

**Comment by dpaulson45** [comment]
We can handle this pretty easy in the new branch of Dev3.0.0. There we only have a single method that handles the scenario of Invoke-Command within Invoke-ScriptBlockHandler. 

@JCothern is there any easy way to reproduce that issue within a lab so we can test? I wouldn't think by declaring for us to use no proxy servers within the command should break anything, but we should test internally as well.
