### ISSUE TITLE
Unhandled exception if GitHub API rate limit exceeded in Test-ScriptVersion in Dev3.0.0

### ISSUE THREAD

**Issue by lusassl-msft** [dpaulson45/HealthChecker#326]
We should handle the following exception in Test-ScriptVersion:

```
Errors that occurred that wasn't handled
{"message":"API rate limit exceeded for 123.123.123.123. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
    + PSComputerName        : localhost
```

**Comment by lusassl-msft** [comment]
This should do the job:

Is:
`$releaseInformation = Receive-Job -Id $WebRequestJob.Id -Keep`

Should:
`if(!(Receive-Job -Id $WebRequestJob.Id -Keep)){Invoke-CatchActions}else{$releaseInformation = Receive-Job -Id $WebRequestJob.Id -Keep}`

**Comment by lusassl-msft** [comment]
@dpaulson45 We've addressed this issue in v2 with `Receive-Job -Id $WebRequestJob.Id -Keep -ErrorAction Stop`. Let's decide if we handle it also this way in Dev3.0.0 or implement the solution from above.

**Comment by dpaulson45** [comment]
@lusassl-msft can you find the commit?

**Comment by lusassl-msft** [comment]
Yep, found it. It's #270 so this work item is a dup.

**Comment by lusassl-msft** [comment]
I think the solution listed here is better because it doesn't break the function and Remove-Job is executed because we don't end in the catch block.

**Comment by dpaulson45** [comment]
The adding of -ErrorAction Stop or the new one you provided?

**Comment by lusassl-msft** [comment]
The new one works better in my opinion.

**Comment by dpaulson45** [comment]
I am thinking this would be better, but not sure if it would work. Can you test? 

```
                    Write-VerboseOutput("WebRequest after {0} attempts successfully completed. Receiving results." -f $i)

                    try
                    {
                        $releaseInformation = Receive-Job -Id $WebRequestJob.Id -Keep -ErrorAction Stop
                    }
                    catch
                    {
                        if ($CatchActionFunction -ne $null)
                        {
                            & $CatchActionFunction
                        }
                    }

                    Write-VerboseOutput("Removing background worker job")
```

Passing $CatchActionFunction as a variable of course.

**Comment by lusassl-msft** [comment]
Will validate your solution on Monday

**Comment by lusassl-msft** [comment]
Seems to be a working solution:
Added this parameter to Test-ScriptVersion:
`[Parameter(Mandatory=$false)][scriptblock]$CatchActionFunction`

Code improvements:
```
                    Write-VerboseOutput("WebRequest after {0} attempts successfully completed. Receiving results." -f $i)
                    try
                    {
                        $releaseInformation = Receive-Job -Id $WebRequestJob.Id -Keep -ErrorAction Stop
                    }
                    catch
                    {
                        if ($CatchActionFunction -ne $null)
                        {
                            & $CatchActionFunction
                        }
                    }
```

Call it this way:
`$currentVersion = Test-ScriptVersion -ApiUri "api.github.com" -RepoOwner "dpaulson45" -RepoName "HealthChecker" -CurrentVersion $healthCheckerVersion -DaysOldLimit 90 -CatchActionFunction {Invoke-CatchActions}`
