### ISSUE TITLE
Exchange 2019 Page file size check

### ISSUE THREAD

**Issue by ChrisMKV** [dpaulson45/HealthChecker#328]
For Exchange 2019, the Page file size recommendation has changed, it is now 25% of installed memory:
https://docs.microsoft.com/en-us/exchange/plan-and-deploy/system-requirements?view=exchserver-2019

Currently this configuration generates a failure on the Health Check, I suppose it is expecting Memory + 10% as was best practice in earlier versions.

**Comment by dpaulson45** [comment]
@ChrisMKV it should be checking for 25% of the installed memory for 2019. Please email ExToolsFeedback@microsoft.com with the output of the 2 files so i can look it over.

**Comment by dpaulson45** [comment]
https://github.com/dpaulson45/HealthChecker/issues/85

6f581119ebf253ed33ff3a3cf20e05517702d9b0

**Comment by lusassl-msft** [comment]
@ChrisMKV make sure that you use the latest HealthChecker release (https://github.com/dpaulson45/HealthChecker/releases/tag/v2.43.0). If you're already using it, follow David's instructions. Thanks.

**Comment by ChrisMKV** [comment]
Thanks @lusassl-msft , looks like I had an older version of the script. In the latest one the check is passed.
Cheers!
