### ISSUE TITLE
Fix display wording on recommended .NET version

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/HealthChecker#333]
Currently seeing something like this:

.NET Framework: 4.8 - Warning Recommended .NET Version is Net4d8

Change the Net4d8 to a friendly name.

**Comment by dpaulson45** [comment]
Also, we are clearly on the correct version. This is on SOLO-E19A need to figure out why this is occurring.

**Comment by lusassl-msft** [comment]
@dpaulson45 have not checked yet, but it may happen because of the not properly working OSDetection for Windows2019 #336

**Comment by dpaulson45** [comment]
@lusassl-msft doesn't appear to fix that.

**Comment by lusassl-msft** [comment]
@dpaulson45 we need to improve the .Net check to work properly on Windows 2019 (see #249):

```
.NET Framework 4.8
On Windows 10 May 2019 Update and Windows 10 November 2019 Update: 528040
On Windows 10 May 2020 Update: 528372
On all other Windows operating systems (including other Windows 10 operating systems): 528049
```
https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed

**Comment by dpaulson45** [comment]
@lusassl-msft please confirm that this version of the script does address the issue on Windows 2019 for .NET framework.

**Comment by lusassl-msft** [comment]
@dpaulson45 looks good so far. Let's merge #380
