### ISSUE TITLE
Add Check for NIC Power management setting - Dev3.0.0

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/HealthChecker#342]
Add PR 341 to Dev3.0.0

**Comment by lusassl-msft** [comment]
@dpaulson45 let me check if I can adopt this to v3

**Comment by dpaulson45** [comment]
@lusassl-msft i was actually going to work on the last two issues here this morning. What I can use is test out in labs the v3, making sure everything looks right there. Also need you to look over the HTML results for multiple servers and see how that looks, if there is anything we want to add or remove from it for initial release.

**Comment by lusassl-msft** [comment]
@dpaulson45 okay, I'm going to improve the check a little bit (for example adding all the possible combinations for power saving options to it). When you're done with implementation to v3 I'll add the additional states to the switch.

I'll take care of the testing. Will do this tomorrow at the latest.

**Comment by lusassl-msft** [comment]
@dpaulson45 I'm not sure if we should limit this only to hardware. VMWare virtual NICs does also support this function (see screenshot):

![image](https://user-images.githubusercontent.com/40993616/98218896-9a33e580-1f4c-11eb-83eb-6a7f130bc059.png)
