### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by worldsdream** [dpaulson45/HealthChecker#346]
Hi there,

Is it possible to work again with milestones? This way it’s easier to check whats added or fixed in each release.  

I also don’t see a changelog at each release version, can this be added?

Also, if you need a beta tester. Just mention me at a feature or fix, and let me know what to check.

**Comment by dpaulson45** [comment]
@worldsdream I use to use milestones, but i think the problem with the milestones that i didn't like was i couldn't take a work item to multiple milestones. I can look at adding that back into my routine for items. I just checkout out how vscode does us it and that doesn't look like a bad idea. 

However, i am thinking about changing how we do releases. Right now I try to not make releases too often and try to wait to add features till like a security release is done or new CUs are released, unless i have a new check that i want to include right away as we see a few different cases on them. 

As for the change log, are you thinking this on the Release page itself or a file/section in the readme similar to this: https://github.com/microsoft/ExPerfAnalyzer#changelog

We will keep that in mind in regards to the beta tester for anything specific that we need. We are actual looking forward to getting pester into the project to handle a lot of our testing in the future.

**Comment by worldsdream** [comment]
@dpaulson45 Milestones are great so the people know what fixes and featurs we can expect in the next release. That would be very great to have. 

Yes a changelog like that is perfect! If you could add that in each release, it will help a lot. 

Thank you for your work that you and the others put in.

**Comment by worldsdream** [comment]
I recommend to only have a release changelog on github (release page) and not in the readme text file.

It’s easier to maintain and it’s modern. Back in the days a changelog with a readme.txt was ok. 

Nowadays we immediately go the webpage and check the latest content.

**Comment by dpaulson45** [comment]
@worldsdream instead of a change log in the repro, what do you think of the commits on the release page?

**Comment by worldsdream** [comment]
@dpaulson45 That’ perfect!

**Comment by worldsdream** [comment]
Closing because @dpaulson45 added the commits in release page.
