### ISSUE TITLE
Remove LoadBalancingReport and/or MailboxReport and/or DCCoreRatio

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/HealthChecker#398]
Not sure how often these features are used. Do we want to move them out of the script or not. 

@lusassl-msft can you get some feedback on this as well.

**Comment by dpaulson45** [comment]
@lusassl-msft did you ever get any feedback on this?

**Comment by lusassl-msft** [comment]
Unfortunately, not really. I'll shout out for feedback one more time with the next release and we should then decide how to proceed.

**Comment by dpaulson45** [comment]
@lusassl-msft how is that feedback coming on this?

**Comment by lusassl-msft** [comment]
Let me share some feedback:

**How often do you use the Health Checker Load Balancing Report feature?**
![image](https://user-images.githubusercontent.com/40993616/104462601-141dc600-55b1-11eb-8b82-f6b37ba851ce.png)

**Should we keep the Load Balancing Report feature as part of the Health Checker or do you want to have this to become an extra script?**
![image](https://user-images.githubusercontent.com/40993616/104462651-24ce3c00-55b1-11eb-934f-94cdf9ebbb45.png)

**How often do you use the Health Checker Mailbox Report feature?**
![image](https://user-images.githubusercontent.com/40993616/104462711-344d8500-55b1-11eb-9eab-b69f1cad64dc.png)

**Should we keep the Mailbox Report feature as part of the Health Checker or do you want to have this to become an extra script?**
![image](https://user-images.githubusercontent.com/40993616/104462771-43ccce00-55b1-11eb-8b0e-9136f81c3404.png)

**How often do you use the Health Checker DC Core Ratio feature?**
![image](https://user-images.githubusercontent.com/40993616/104462828-52b38080-55b1-11eb-9548-473835aa14e0.png)

**Should we keep the DC Core Ratio feature as part of the Health Checker or do you want to have this to become an extra script?**
![image](https://user-images.githubusercontent.com/40993616/104462894-652dba00-55b1-11eb-83a1-8e327d4b4fbe.png)

**Comment by lusassl-msft** [comment]
Most participants of our survey would like to see the functions remain part of the script.

**Comment by dpaulson45** [comment]
Interesting, especially about the DC Core Ratio. That doesn't work unless you have permissions to both Exchange and the DCs. But okay I guess, we will keep them.

Closing down the issue.
