### ISSUE TITLE
Consider refactoring logging functions

### ISSUE THREAD

**Issue by mynamewastaken** [dpaulson45/HealthChecker#40]
https://github.com/dpaulson45/HealthChecker/blob/15ffd766fa519e60bd4c72e5fceda4a664e8278d/HealthChecker.ps1#L375

Consider making one function and passing the message and the color to log as arguments. e.g.:
```
function Write-Color($message, $color)
{
    Write-Host $message -ForegroundColor $color
    $message | Out-File ($OutputFullPath) -Append
}
```

**Comment by dpaulson45** [comment]
I thought about doing that when i was first creating the script, but i figured this was easier to read for some people.
