### ISSUE TITLE
Get-NicPnpCapabilitiesSetting function not probing all NICs

### ISSUE THREAD

**Issue by geo-it** [dpaulson45/HealthChecker#405]
The Get-NicPnpCapabilitiesSetting function exits early if network adapter registry keys are not contiguous. As a consequence SleepyNicDisabled is possibly not output correctly.

I have a system that has this NIC registry storage structure:
{4d36e972-e325-11ce-bfc1-08002be10318}
0000
0001
0003
0004
Configuration

Get-NicPnpCapabilitiesSetting exits after 0001 because of its while loop structure.

**Comment by lusassl-msft** [comment]
Hi,
Could you please run the script with `-verbose` switch and send us the log to `extoolsfeedback[at]microsoft.com`

**Comment by geo-it** [comment]
Done. Log shows it not continuing after failing to find NetCfgInstanceId on the 0002 subkey which does not exist.

I only looked because I was sure I had remediated my SleepyNicDisabled condition but it still reports False. Maybe the SleepyNicDisabled should default to Unknown instead of False and only report False or True if it actually determines the issue state?

**Comment by lusassl-msft** [comment]
Thanks @geo-it . I’ve also received your debug log. Will have a look at it on Monday. Thanks for reporting this issue.

**Comment by dpaulson45** [comment]
We should be able to return the RegKey from Invoke-RegistryGetValue and then use GetSubKeyNames() to find all the possible outputs starting with 0, then just use that list in a foreach loop vs a while loop. 

```
[PS] C:\Windows\system32>$regKey.GetSubKeyNames()
0000
0001
0002
0003
0004
0005
0006
0007
0008
0009
0010
0011
0012
0013
Configuration
Properties

[PS] C:\Windows\system32>$regKey.GetSubKeyNames() |?{$_.StartsWith("0")}
0000
0001
0002
0003
0004
0005
0006
0007
0008
0009
0010
0011
0012
0013
```

**Comment by lusassl-msft** [comment]
@geo-it I've checked in a fix to address this issue. Feel free to try it. It's PR #407

**Comment by geo-it** [comment]
Works great. Thank you.
