### ISSUE TITLE
Version 3.0.0 gives security warning but system is patched

### ISSUE THREAD

**Issue by habo105** [dpaulson45/HealthChecker#406]
Hi,

On Exchange 2016 CU17 version 3.0.0 gives this errors:

![image](https://user-images.githubusercontent.com/54137537/99245367-bf094200-2803-11eb-8106-7d75ae62b97c.png)

But the system is patched to solve these errors (confirmed by the healthchecker script):

![image](https://user-images.githubusercontent.com/54137537/99245499-f546c180-2803-11eb-9d19-f4b0dca4cd17.png)

Can this be solved?

**Comment by lusassl-msft** [comment]
Hi @habo105 ,
Could you please run the script with `-verbose` switch and send us the log to `extoolsfeedback[at]microsoft.com`

**Comment by entmgmt** [comment]
Looks like this issue is resolved now when I pulled the latest release yesterday.

**Comment by lusassl-msft** [comment]
@entmgmt you've installed the latest CU, right?

**Comment by entmgmt** [comment]
Yes, all the latest CU's are installed and are identified by the script and no updates / CVE's are being listed in RED .

**Comment by lusassl-msft** [comment]
That is what we also found out. PR #408 solves the issue even if the CU is not the current one.
