### ISSUE TITLE
Warning IPv6 is not enabled !

### ISSUE THREAD

**Issue by entmgmt** [dpaulson45/HealthChecker#410]
While running the script, the below is thrown in YELLOW
`IPv6 Enabled: False --- Warning`

However, IPv6 is enabled and is checked as: 
**Get-NetAdapterBinding -ComponentID ms_tcpip6 | fl *** Results in **Enabled : True**

Note that the Adapter has it enabled and is set as **DHCP = TRUE** . However there are no DHCP IPv6 servers in our environment.

This warning was thrown in the previous releases also.

**Comment by dpaulson45** [comment]
@entmgmt thanks for reporting this issue. This will be addressed in v3.0.1 as this has already been resolved in #402
