### ISSUE TITLE
Errors with & and < characters

### ISSUE THREAD

**Issue by falarcon10** [dpaulson45/HealthChecker#424]
I am trying to run a script on Exchange 2016 CU16 and I am getting the following error messages

_En C:\TEMP\HealthChecker.ps1: 166 Carácter: 21
+                 Sign&nbsp;up
+                     ~
No se permite usar el carácter de Y comercial (&). El operador & está reservado para un uso futuro; encierre un símbolo de Y comercial entre comillas dobles ("&") para 
pasarlo como parte de una cadena.
En C:\TEMP\HealthChecker.ps1: 193 Carácter: 190
+ ... ata-ga-click="(Logged out) Header, go to Features">Features <span cla ...
+                                                                 ~
El operador '<' está reservado para uso futuro.
En C:\TEMP\HealthChecker.ps1: 193 Carácter: 261
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
No se permite usar el carácter de Y comercial (&). El operador & está reservado para un uso futuro; encierre un símbolo de Y comercial entre comillas dobles ("&") para 
pasarlo como parte de una cadena.
En C:\TEMP\HealthChecker.ps1: 207 Carácter: 255
+ ... ogged out) Header, go to Customer stories">Customer stories <span cla ...
+                                                                 ~
El operador '<' está reservado para uso futuro.
En C:\TEMP\HealthChecker.ps1: 207 Carácter: 326
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
No se permite usar el carácter de Y comercial (&). El operador & está reservado para un uso futuro; encierre un símbolo de Y comercial entre comillas dobles ("&") para 
pasarlo como parte de una cadena.
En C:\TEMP\HealthChecker.ps1: 208 Carácter: 231
+ ... ata-ga-click="(Logged out) Header, go to Security">Security <span cla ...
+                                                                 ~
El operador '<' está reservado para uso futuro.
En C:\TEMP\HealthChecker.ps1: 208 Carácter: 302
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
No se permite usar el carácter de Y comercial (&). El operador & está reservado para un uso futuro; encierre un símbolo de Y comercial entre comillas dobles ("&") para 
pasarlo como parte de una cadena.
En C:\TEMP\HealthChecker.ps1: 231 Carácter: 222
+ ... a-click="(Logged out) Header, go to Explore">Explore GitHub <span cla ...
+                                                                 ~
El operador '<' está reservado para uso futuro.
En C:\TEMP\HealthChecker.ps1: 231 Carácter: 293
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
No se permite usar el carácter de Y comercial (&). El operador & está reservado para un uso futuro; encierre un símbolo de Y comercial entre comillas dobles ("&") para 
pasarlo como parte de una cadena.
En C:\TEMP\HealthChecker.ps1: 234 Carácter: 107
+ ...  text-normal text-mono f5 mb-2 border-lg-top pt-lg-3">Learn &amp; con ...
+                                                                 ~
No se permite usar el carácter de Y comercial (&). El operador & está reservado para un uso futuro; encierre un símbolo de Y comercial entre comillas dobles ("&") para 
pasarlo como parte de una cadena.
No se notificaron todos los errores de análisis. Corrija los errores notificados e inténtelo de nuevo.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed_

**Comment by dpaulson45** [comment]
Please do not copy the script out of the web browser and paste it in. This is how you get this error. Download the script from the Releases page here: https://github.com/dpaulson45/HealthChecker/releases

**Comment by falarcon10** [comment]
Sorry for the inconvenience David.
I have downloaded the script from this link and it worked correctly.
Thanks
