### ISSUE TITLE
Exchange Server 2016 (Build 2106.2) not identified as local Exchange Server

### ISSUE THREAD

**Issue by Apoc70** [dpaulson45/HealthChecker#435]
The script does not identify an Exchange Server 2016 (new CU18 install) as a local Exchange Server when executed in a non-EMS-PowerShell session. 

HKLM:\SOFTWARE\Microsoft\ExchangeServer\v15\Setup is missing

![image](https://user-images.githubusercontent.com/11044567/101758948-42ebdc80-3ad9-11eb-873c-a2ae4cc9de2c.png)

The Exchange Server setup completed successfully and the server is fully operational. So I do not know if this is a setup anomaly.

The current release works fine when started in an EMS session.

**Comment by lusassl-msft** [comment]
Thanks for reporting this @Apoc70 . @dpaulson45 I'm not sure if this is by design or an issue. We could check for `HKLM:\SOFTWARE\Microsoft\ExchangeServer\v15\MailboxRole` or `HKLM:\SOFTWARE\Microsoft\ExchangeServer\v15\ClientAccessRole`. One of these should be available. What do you think?

**Comment by dpaulson45** [comment]
@Apoc70 i would like to review the debug log of this scenario to understand it more. Not sure why in EMS would work and PowerShell doesn't.

Can you send the debug log to `ExToolsFeedback@microsoft.com`

**Comment by dpaulson45** [comment]
@Apoc70 are you able to send that information?

**Comment by Apoc70** [comment]
@dpaulson45 I will send it by tomorrow.

**Comment by lusassl-msft** [comment]
@dpaulson45 I think we see this behavior because we call this after the `if / else` block within the `Confirm-ExchangeShell` function: 
`Write-VerboseWriter("Returned: {0}" -f $passed)
return $passed`

It’s no problem when executed in EMS, but it is when executed in PowerShell because we don’t load the Exchange Remote Management shell which we normally do within the `if` block.

**Comment by lusassl-msft** [comment]
Okay, forget my comment from yesterday. It's never a good idea to check code using a mobile phone. 
I've checked the code again using my desktop and I think I've found the reason for the behavior. 
@Apoc70 how do you run the script to repro the above-described behavior? Do you use the `-Server` parameter? If you do, do you use the Fqdn here?

If that's the case we then have the following condition:

`    if ($Script:Server -ne $env:COMPUTERNAME)
    {
        $byPassLocalExchangeServerTest = $true
    }
`

Condition that is checked / passed successful in the `Confirm-ExchangeShell` function in this case:

`    if(($isLocalExchangeServer = (Test-Path 'HKLM:\SOFTWARE\Microsoft\ExchangeServer\v14\Setup')) -or
    ($isLocalExchangeServer = (Test-Path 'HKLM:\SOFTWARE\Microsoft\ExchangeServer\v15\Setup')) -or
    $ByPassLocalExchangeServerTest)
`

We then pass the logic and at the end successfully loading the Exchange PowerShell module:

`                        Import-Module $env:ExchangeInstallPath\bin\RemoteExchange.ps1 -ErrorAction Stop
                        Connect-ExchangeServer -Auto -ClientApplication:ManagementShell
                        $passed = $true #We are just going to assume this passed.
`

**Comment by Apoc70** [comment]
@lusassl-msft, I use the following command to reproduce the behavior in a non-EMS PowerShell session.

` .\HealthChecker.ps1 -Debug`

The behavior is the same for an elevated or non-elevated PS-Session. 

The referenced registry path 'HKLM:\SOFTWARE\Microsoft\ExchangeServer\v15\Setup' does not exist on that particular server. 
I installed Exchange Server 10 days ago using build 15.1.2106.2 and the setup finished successfully.

**Comment by lusassl-msft** [comment]
@Apoc70 hm okay, let's have a look at the debug logs.
