### ISSUE TITLE
null-valued expression on certificates

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/HealthChecker#436]
Customer reported this issue

```
You cannot call a method on a null-valued expression.
At E:\tools\HealthChecker.ps1:4133 char:8
+     if($exchangeInformation.ExchangeCertificates.IsCurrentAuthConfigCertificate. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

Need to be able to handle if `ExchangeCertificates` is `null` as I believe is the cause. However, I could be wrong.

**Comment by lusassl-msft** [comment]
Please assign to me. If auth cert is empty, it’s an Exchange issue (https://www.nucleustechnologies.com/blog/resolve-the-auth-certificate-missing-error-in-exchange-2016-2013/). We should highlight this case in red.

**Comment by lusassl-msft** [comment]
Tried to reproduce this issue but without success. Any chance to get the debug log output?

**Comment by dpaulson45** [comment]
No, I don't have it. The engineer only gave me the normal log output file.

**Comment by lusassl-msft** [comment]
Okay, will spend more time trying to repel this behavior
