### ISSUE TITLE
Can we use multiple Exchange Servers in the parameter?

### ISSUE THREAD

**Issue by worldsdream** [dpaulson45/HealthChecker#444]
Hi,

I tried to run `.\HealthChecker.ps1 -Server EX01,EX02`

The output is:
```
[C:\HealthChecker.ps1 : Cannot process argument transformation on parameter 'Server'. Cannot convert value to type System.String.
At line:1 char:29]
```

Can you give us the option to include more than one Exchange Server? And can you let us know how to export a health check on all the Exchange Servers? For example `.\HealthChecker.ps1 -Server "All"`

Thank you.

**Comment by lusassl-msft** [comment]
Hi @worldsdream,
this feature is already on our backlog and planned for a future release.

https://github.com/dpaulson45/HealthChecker/projects/2#card-21564295

**Comment by lusassl-msft** [comment]
Hi @worldsdream,
this feature is already in our backlog. 

https://github.com/dpaulson45/HealthChecker/issues/158

**Comment by worldsdream** [comment]
Thank you @lusassl-msft. I will close this then and follow the feature.
