### ISSUE TITLE
Missing AmazonEC2 server type from v2

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/HealthChecker#447]
In version 2 of the Health Checker, we called out AmazonEC2 as a server type. 

Need to port over changes from d73357d68e5520d8ab736d2571aa10e08358a00a

**Comment by lusassl-msft** [comment]
We already do in v3:

`            //enum for the type of computer that we are
            public enum ServerType
            {
                VMWare,
                AmazonEC2,
                HyperV,
                Physical,
                Unknown
            }`

We use this server type in the following sections:

- Processor/Hardware Information
- NIC Settings Per Active Adapter

Did we miss some?

**Comment by dpaulson45** [comment]
@lusassl-msft it isn't included in Get-ServerType which is the main piece.
