### ISSUE TITLE
Handle null Hashtable of ApplicationPools

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/HealthChecker#449]
Customer reported the following error message:

```
Cannot index into a null array.
At C:\HealthChecker.ps1:2988 char:9
+         $content = [xml]$exchangeInformation.ApplicationPools["MSExchangeMapiFro ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
```

We don't want to halt the script for this issue, we should just handled it and provide a warning if it is `$null `

**Comment by lusassl-msft** [comment]
Do you know if `MSExchangeMapiFrontEndAppPool` is available when Mapi/HTTP is not configured on Exchange 2013?

**Comment by dpaulson45** [comment]
Yep, it is. We just enable a setting in AD when we set it to enabled.

But the error here: 

```
$content = [xml]$exchangeInformation.ApplicationPools["MSExchangeMapiFrontEndAppPool"].Content
```

The exception is `Cannot index into a null array.` which is providing that `ApplicationPools` is null and not initialized. As that is the only thing in this line that is trying to index into something.

**Comment by lusassl-msft** [comment]
Agree. Based on the provided debug log it looks like we're failing to `$exchangeAppPoolsInfo = Invoke-ScriptBlockHandler -ComputerName $Script:Server -ScriptBlock ${Function:Get-ExchangeAppPoolsScriptBlock} -ScriptBlockDescription "Getting Exchange App Pool information" -CatchActionFunction ${Function:Invoke-CatchActions}` within `Get-ExchangeAppPoolsInformation` function. This causes `$exchangeInformation.ApplicationPools = Get-ExchangeAppPoolsInformation` not to be initialized or to be zero which ends up in the exception.

**Comment by dpaulson45** [comment]
yeah, one way to fix that is to initialize it on the class creation in the `Add-Type`.

```
public Hashtable ApplicationPools = new Hashtable();
```

This way we shouldn't get the above error, but we would still need to make sure that we handle the `$null` results if we don't find that key.
