### ISSUE TITLE
Invoke-Command fails when using IPv6 and WSMan:\localhost\Service\IPv6Filter isn't allowing a wildcard

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/HealthChecker#474]
Nothing was working properly when it came to commands that relied on `WSMan` due to the fact that the server still had IPv6 enabled and yet `WSMan` was blocking this version. This caused a lot of false information to occur within the script and yet appeared to be working just fine.

Repro Steps:

- Have an Exchange Server set to be using IPv6
- Confirm that when hitting the server name that we are using IPv6 `ping $env:COMPUTERNAME`
- Run the following command on the server `Set-Item WSMan:\localhost\Service\IPv6Filter -Value " "`
- Run the Health Checker script and notice a lot more issues for all scenarios where we call `Invoke-Command`

**Comment by lusassl-msft** [comment]
We should consider running `Invoke-Command` with localhost instead of NetBIOS or FQDN if the script is executed directly on the system to be checked.

![image](https://user-images.githubusercontent.com/40993616/105149474-dca89f80-5b03-11eb-9076-3ab7d7752aaa.png)

**Comment by dpaulson45** [comment]
It would be better to just improve the logic for testing to switch to use the FQDN. If we would have kept the `$env:COMPUTERNAME` in the `$Script:Server` to begin with, we shouldn't have run into an issue as this would have been all executed locally vs inside of an `scriptblock` in a `Invoke-Command`.

Only part that might have run into issues would have been getting the NIC information with the `New-CimSession` as I believe that would still use WSMan which we could also look into fixing.

**Comment by lusassl-msft** [comment]
I ran into the same issue when using the NetBIOS name only. Need more time for investigation but should be possible to fix this behavior.

**Comment by dpaulson45** [comment]
You shouldn't when using `Invoke-ScriptBlockHandler` as that has logic to just invoke the `ScriptBlock` locally without using `Invoke-Command`.

**Comment by lusassl-msft** [comment]
Yes, you’re right. My comment was incomplete. It was related to my test in the screenshot. Should I take care of this issue or are you already working on it? If not, please assign :-)
