### ISSUE TITLE
[Issue] Page file warning message

### ISSUE THREAD

**Issue by serhatakinci** [dpaulson45/HealthChecker#528]
When I try to run HealthChecker.ps1 on Exchange Server 2016 with more than 32GB RAM installed server, script reports "Pagefile should be capped at 32778MB for 32GB plus 10MB" warning message. But paging file value specified 32GB (32768MB) for this combination in Exchange Server 2016 requirements document below.

> **Paging file size**
> Set the paging file minimum and maximum value to the same size:
> • Less than 32 GB of RAM installed: Physical RAM plus 10MB, up to a maximum value of 32GB (32,778MB).
> • 32 GB of RAM or more installed: 32GB

https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/system-requirements?view=exchserver-2016#hardware-requirements-for-exchange-2016

**Comment by dpaulson45** [comment]
@serhatakinci they must have changed that as it was originally 32GB + 10MB. 

Here is some 2013 docs on it.
https://docs.microsoft.com/en-us/exchange/exchange-2013-system-requirements-exchange-2013-help#:~:text=Network%20and%20directory%20servers%20%20%20%20Component,Windows%20Serv%20...%20%202%20more%20rows

**Comment by serhatakinci** [comment]
@dpaulson45 If they didn't mistype in the Exchange Server 2016 documentation then it would be better to check pagefile configuration separately for Exchange Server 2016 in the script.

**Comment by FredVH** [comment]
The Exchange Teams says it should be 32GB + 10MB:
Set the paging file minimum and maximum value to the same size. In Exchange 2016 the value should be 32 GB +10MB, unless you have less than 32 GB of RAM, then use the same value of RAM installed plus 10MB. On Exchange 2019, the paging file minimum and maximum should be set to 25% of installed memory.
https://techcommunity.microsoft.com/t5/exchange-team-blog/checklist-for-troubleshooting-performance-related-issues-in/ba-p/604792

**Comment by lusassl-msft** [comment]
Indeed. We'll update the documentation soon. Thanks for bringing this to our attention.

**Comment by lusassl-msft** [comment]
Typo corrected:
![image](https://user-images.githubusercontent.com/40993616/111960002-78985c80-8aef-11eb-90a2-4738e6ce3e1d.png)

@dpaulson45 issue can be closed

**Comment by serhatakinci** [comment]
Good news :)
