### ISSUE TITLE
[Issue] Multiple Sleepy NIC Detection Issue

### ISSUE THREAD

**Issue by serhatakinci** [dpaulson45/HealthChecker#535]
When I run HealthChecker.ps1 on a Windows Server 2016 with multiple network adapters, script reports "Sleepy NIC Disabled: False" warning message for one of the network adapters. However `PnPCapabilities` registry value is tuned to `24` for all adapters on the server.

I debug the code. If server has more than one network adapter and also device numbers don't exist sequentially in the registry (example below), `Get-NicPnpCapabilitiesSetting` function cannot handle this scenario correctly because `$i` variable increases sequentialy but in some systems device numbers don't, so in this case function ends (do while iteration) and misses some adapters.

```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{4d36e972-e325-11ce-bfc1-08002be10318}
> 0000 (Interface1, MAPI)
> 0001
> 0002
> 0004 (Interface2, Replication)
> 0005
> 0006
```

In the example above, 0003 key doesn't exits so function stops after key 0002 and misses the adapter with device number 0004.

**Comment by lusassl-msft** [comment]
Sounds like a regression. Will have a look at it. @dpaulson45 please assign to me.

**Comment by lusassl-msft** [comment]
@serhatakinci I've checked in a PR for the external `Get-AllNicInformation` function to address this issue. Please find it here: https://github.com/dpaulson45/PublicPowerShellFunctions/pull/10
