### ISSUE TITLE
[Work Item] Identify Missing DLLs on the Exchange Server

### ISSUE THREAD

**Issue by PKs-Haus** [dpaulson45/HealthChecker#536]
**Describe the work**
Identify Missing Dlls

**Additional Context**
Can you add code to do a Dll check and output list of missing Dlls? I am seeing alot of this taking place.

**Comment by lusassl-msft** [comment]
Hi @PKs-Haus,
can you please describe the requirement in more detail?

Thanks

**Comment by PKs-Haus** [comment]
One of the items that we find missing frequently are DLLs. If this script had a means of identifying the missing dlls and easily replace them.

**Comment by dpaulson45** [comment]
Yes, i think this is something that I should do. Just not 100% sure if i will place it in the Health Checker script though. More to come once i think about it some more.

**Comment by lusassl-msft** [comment]
@PKs-Haus we now have the following script for doing this job: 
https://github.com/microsoft/CSS-Exchange/releases/latest/download/CopyMissingDlls.ps1

**Comment by dpaulson45** [comment]
Different script was created to help handle this. This is also outside the scope of this script.
