### ISSUE TITLE
Please document the versions of Exchange Server that this script works with. To my knowledge it is only Exchange Server 2013 and newer. I don't see documentation on this page or within the script stating this.

### ISSUE THREAD

**Issue by M34U2NV** [dpaulson45/HealthChecker#537]
**Describe the issue**
A clear and concise description of what the issue is.

**Expected behavior**

**Script Output**
If applicable, add the exception that you are seeing that wasn't handled.

**Additional context**

**Comment by lusassl-msft** [comment]
Supported versions will be added to the Readme with #540 . We are still evaluating whether this will also be tested in the script.
