### ISSUE TITLE
[New Check] Check installed UCMA version

### ISSUE THREAD

**Issue by JustinHoeky** [dpaulson45/HealthChecker#538]
**Describe the issue**
Currently Microsoft offers UCMA 4.0 as required for a 2013/2016/2019 Exchange installation.
UCMA 4.0 is outdated and not supported anymore on Server 2016 and 2019.
UCMA 6.0 is the latest supported version (which currently has some issues which Microsoft does not seem to have fixed)

**Additional context**
Source: https://docs.microsoft.com/en-us/answers/questions/167684/exchange-2016-exchange-2019-wrong-recommendations.html

**Comment by lusassl-msft** [comment]
Thanks for reporting @JustinHoeky. I was not aware of this behavior. Let me check internally with the Exchange team.

**Comment by JustinHoeky** [comment]
> Thanks for reporting @JustinHoeky. I was not aware of this behavior. Let me check internally with the Exchange team.

Thank you @lusassl-msft 
Would be great to see it fixed so I can upgrade without the extra steps. Seems like a wrong hardcoded version as stated in the article I linked.

Kind regards

**Comment by lusassl-msft** [comment]
@JustinHoeky engineering is now aware of this. Will leave this work item open until we have a decision. We then decide if and how to implement this in Health Checker.

**Comment by JustinHoeky** [comment]
@lusassl-msft any news on the UCMA 6 fix?
Got 3 more Sysadmin interested for a fix while talking about it.

Kind regards

**Comment by lusassl-msft** [comment]
Not yet. The team is busy working on the current releases. Be sure that it's on someone's backlog. I'll keep you posted as soon as we have more information available.

**Comment by Karl-WE** [comment]
@JustinHoeky thanks for referring to my Q&A article. Glad to see it is "visible". Recently spoke to someone at twitter that like to pass this on to the Exchange Team. 
Replacing UCMA is not that easy as the installer has hardcoded C++ Redist version check, so one has to uninstall the C++ 2015-2019 package and install the lastet after UCMA 6.0 install obtainable here:
https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

**Comment by JustinHoeky** [comment]
> @JustinHoeky thanks for referring to my Q&A article. Glad to see it is "visible". Recently spoke to someone at twitter that like to pass this on to the Exchange Team.
> Replacing UCMA is not that easy as the installer has hardcoded C++ Redist version check, so one has to uninstall the C++ 2015-2019 package and install the lastet after UCMA 6.0 install obtainable here:
> https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

Hi @Karl-WE
It needed some extra attention, hope they can fix it so we can update it more easily without the extra steps of uninstalling software and replace it with a 2018 version.
