### ISSUE TITLE
Exchange 2010 Script Errors

### ISSUE THREAD

**Issue by PowerPress** [dpaulson45/HealthChecker#541]
**Describe the issue**
Receiving error when script is ran from Administrator on on Exchange 2010 EMC

**Expected behavior**
No errors to be returned and output provided

**Script Output**
[PS] C:\Users\user\Desktop>.\HealthChecker.ps1
WriteToFileOnly : You cannot call a method on a null-valued expression.
At C:\Users\user\Desktop\HealthChecker.ps1:1071 char:39
+         $Script:Logger.WriteToFileOnly <<<< ($message)
    + CategoryInfo          : InvalidOperation: (WriteToFileOnly:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Out-File : Cannot bind argument to parameter 'FilePath' because it is null.
At C:\Users\user\Desktop\HealthChecker.ps1:1058 char:24
+     $message | Out-File <<<<  ($OutputFullPath) -Append
    + CategoryInfo          : InvalidData: (:) [Out-File], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.OutFileComm
   and

WriteToFileOnly : You cannot call a method on a null-valued expression.
At C:\Users\user\Desktop\HealthChecker.ps1:1071 char:39
+         $Script:Logger.WriteToFileOnly <<<< ($message)
    + CategoryInfo          : InvalidOperation: (WriteToFileOnly:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Out-File : Cannot bind argument to parameter 'FilePath' because it is null.
At C:\Users\user\Desktop\HealthChecker.ps1:1058 char:24
+     $message | Out-File <<<<  ($OutputFullPath) -Append
    + CategoryInfo          : InvalidData: (:) [Out-File], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.OutFileComm
   and

WriteToFileOnly : You cannot call a method on a null-valued expression.
At C:\Users\user\Desktop\HealthChecker.ps1:1071 char:39
+         $Script:Logger.WriteToFileOnly <<<< ($message)
    + CategoryInfo          : InvalidOperation: (WriteToFileOnly:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

There appears to have been some errors in the script. To assist with debugging of the script, please send the HealthChec
ker-Debug_*.txt, HealthChecker-Errors.json, and .xml file to ExToolsFeedback@microsoft.com.
Out-File : Cannot bind argument to parameter 'FilePath' because it is null.
At C:\Users\user\Desktop\HealthChecker.ps1:1040 char:24
+     $message | Out-File <<<<  ($OutputFullPath) -Append
    + CategoryInfo          : InvalidData: (:) [Out-File], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.OutFileComm
   and

. : Property 'PreventLogCleanup' cannot be found on this object; make sure it exists and is settable.
At C:\Users\user\Desktop\HealthChecker.ps1:4871 char:28
+             $Script:Logger. <<<< PreventLogCleanup = $true
    + CategoryInfo          : InvalidOperation: (PreventLogCleanup:String) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

WriteToFileOnly : You cannot call a method on a null-valued expression.
At C:\Users\user\Desktop\HealthChecker.ps1:1071 char:39
+         $Script:Logger.WriteToFileOnly <<<< ($message)
    + CategoryInfo          : InvalidOperation: (WriteToFileOnly:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Equals : You cannot call a method on a null-valued expression.
At C:\Users\user\Desktop\HealthChecker.ps1:4835 char:49
+                         Where-Object { $_.Equals <<<< ($currentError) }
    + CategoryInfo          : InvalidOperation: (Equals:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

WriteToFileOnly : You cannot call a method on a null-valued expression.
At C:\Users\user\Desktop\HealthChecker.ps1:1071 char:39
+         $Script:Logger.WriteToFileOnly <<<< ($message)
    + CategoryInfo          : InvalidOperation: (WriteToFileOnly:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

WriteToFileOnly : You cannot call a method on a null-valued expression.
At C:\Users\user\Desktop\HealthChecker.ps1:1071 char:39
+         $Script:Logger.WriteToFileOnly <<<< ($message)
    + CategoryInfo          : InvalidOperation: (WriteToFileOnly:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

WriteToFileOnly : You cannot call a method on a null-valued expression.
At C:\Users\user\Desktop\HealthChecker.ps1:1071 char:39
+         $Script:Logger.WriteToFileOnly <<<< ($message)
    + CategoryInfo          : InvalidOperation: (WriteToFileOnly:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

<position> : An error occurred while enumerating through a collection: Collection was modified; enumeration operation m
ay not execute..
At C:\Users\user\Desktop\HealthChecker.ps1:4830 char:13
+              <<<< $Error |
    + CategoryInfo          : InvalidOperation: (System.Collecti...numeratorSimple:ArrayListEnumeratorSimple) [], Runt
   imeException
    + FullyQualifiedErrorId : BadEnumeration

WriteToFileOnly : You cannot call a method on a null-valued expression.
At C:\Users\user\Desktop\HealthChecker.ps1:1071 char:39
+         $Script:Logger.WriteToFileOnly <<<< ($message)
    + CategoryInfo          : InvalidOperation: (WriteToFileOnly:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Equals : You cannot call a method on a null-valued expression.
At C:\Users\user\Desktop\HealthChecker.ps1:4855 char:49
+                         Where-Object { $_.Equals <<<< ($currentError) }
    + CategoryInfo          : InvalidOperation: (Equals:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

<position> : An error occurred while enumerating through a collection: Collection was modified; enumeration operation m
ay not execute..
At C:\Users\user\Desktop\HealthChecker.ps1:4850 char:13
+              <<<< $Error |
    + CategoryInfo          : InvalidOperation: (System.Collecti...numeratorSimple:ArrayListEnumeratorSimple) [], Runt
   imeException
    + FullyQualifiedErrorId : BadEnumeration

WriteToFileOnly : You cannot call a method on a null-valued expression.
At C:\Users\user\Desktop\HealthChecker.ps1:1071 char:39
+         $Script:Logger.WriteToFileOnly <<<< ($message)
    + CategoryInfo          : InvalidOperation: (WriteToFileOnly:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

RemoveLatestLogFile : You cannot call a method on a null-valued expression.
At C:\Users\user\Desktop\HealthChecker.ps1:5661 char:39
+     $Script:Logger.RemoveLatestLogFile <<<< ()
    + CategoryInfo          : InvalidOperation: (RemoveLatestLogFile:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

IsNullOrWhiteSpace : Method invocation failed because [System.String] doesn't contain a method named 'IsNullOrWhiteSpac
e'.
At C:\Users\user\Desktop\HealthChecker.ps1:773 char:37
+     if ([string]::IsNullOrWhiteSpace <<<< ($LogName)) {
    + CategoryInfo          : InvalidOperation: (IsNullOrWhiteSpace:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

**Additional context**

**Comment by lusassl-msft** [comment]
@PowerPress v3 does no longer support Exchange Server 2010. Please use the latest v2 release (https://aka.ms/ExHCDownloadv2) to validate the configuration of your Exchange 2010 server. Please note that this version is no longer maintained, and some checks are not available.
If you want to check the build number of your Exchange 2010 release, just run:

`Get-Command ExSetup | ForEach {$_.FileVersionInfo}`

RU32 (HAFNIUM Defense in Depth) is build `14.3.513.0`
