### ISSUE TITLE
add email capability ?

### ISSUE THREAD

**Issue by Bonj87** [dpaulson45/HealthChecker#555]
I am very very new to github.. not totally new to powershell.. but this may be beyond what i can currently do.
I am wondering if you can add a component to this to send the HTML output of the script via email so it can be a scheduled task to send to the email admins of the server via task manager?

**Comment by dpaulson45** [comment]
Being able to send an email within the script is going to be outside of the scope of what the script is designed for. Especially with `Send-MailMessage` being deprecated.
