### ISSUE TITLE
[Issue] URL Returned in IPv6 isn't properly disabled no longer works.

### ISSUE THREAD

**Issue by Canthv0** [dpaulson45/HealthChecker#558]
**Describe the issue**
IPv6 not properly disabled returns the following:
	Disable IPv6 Correctly: False 
		Error: IPv6 is disabled on some NIC level settings but not fully disabled. DisabledComponents registry key currently set to ''. For details please refer to the following articles: 
		https://docs.microsoft.com/en-us/archive/blogs/rmilne/disabling-ipv6-and-exchange-going-all-the-way 
		https://support.microsoft.com/en-us/help/929852/guidance-for-configuring-ipv6-in-windows-for-advanced-users

**Expected behavior**
The URL Listed:
		https://docs.microsoft.com/en-us/archive/blogs/rmilne/disabling-ipv6-and-exchange-going-all-the-way
Should go to a valid link.  
It does not.

**Additional context**
The current support.microsoft.com link appear to be correctly documenting how to fix IPv6 now.
I would recommend removing the docs.microsoft.com link completly.

**Comment by lusassl-msft** [comment]
Solved with PR #559
