### ISSUE TITLE
[Work Item] SMB1- add link to article

### ISSUE THREAD

**Issue by FredVH** [dpaulson45/HealthChecker#563]
When "SMB1 Installed" returns "True", add a link to https://techcommunity.microsoft.com/t5/exchange-team-blog/exchange-server-and-smbv1/ba-p/1165615

When "SMB1 Blocked" returns "False", add a link to https://techcommunity.microsoft.com/t5/exchange-team-blog/exchange-server-and-smbv1/ba-p/1165615

**Comment by lusassl-msft** [comment]
We are already doing this:

```
$additionalDisplayValue = [string]::Empty
    $smb1Status = $osInformation.Smb1ServerSettings.Smb1Status

    if ($osInformation.BuildInformation.MajorVersion -gt [HealthChecker.OSServerVersion]::Windows2012) {
        $displayValue = "False"
        $writeType = "Green"

        if ($smb1Status -band 1) {
            $displayValue = "Failed to get install status"
            $writeType = "Yellow"
        } elseif ($smb1Status -band 2) {
            $displayValue = "True"
            $writeType = "Red"
            $additionalDisplayValue = "SMB1 should be uninstalled"
        }

        $analyzedResults = Add-AnalyzedResultInformation -Name "SMB1 Installed" -Details $displayValue `
            -DisplayGroupingKey $keySecuritySettings `
            -DisplayWriteType $writeType `
            -AnalyzedInformation $analyzedResults
    }

    $writeType = "Green"
    $displayValue = "True"

    if ($smb1Status -band 8) {
        $displayValue = "Failed to get block status"
        $writeType = "Yellow"
    } elseif ($smb1Status -band 16) {
        $displayValue = "False"
        $writeType = "Red"
        $additionalDisplayValue += " SMB1 should be blocked"
    }

    $analyzedResults = Add-AnalyzedResultInformation -Name "SMB1 Blocked" -Details $displayValue `
        -DisplayGroupingKey $keySecuritySettings `
        -DisplayWriteType $writeType `
        -AnalyzedInformation $analyzedResults

    if ($additionalDisplayValue -ne [string]::Empty) {
        $additionalDisplayValue += "`r`n`t`tMore Information: https://techcommunity.microsoft.com/t5/exchange-team-blog/exchange-server-and-smbv1/ba-p/1165615"

        $analyzedResults = Add-AnalyzedResultInformation -Details $additionalDisplayValue.Trim() `
            -DisplayGroupingKey $keySecuritySettings `
            -DisplayWriteType "Yellow" `
            -DisplayCustomTabNumber 2 `
            -AddHtmlDetailRow $false `
            -AnalyzedInformation $analyzedResults
    }
```

**Comment by FredVH** [comment]
I'm using version v3.3.5, but all I saw was "Ture" and "False":
![ExchangeHealtChecker335_SMB1](https://user-images.githubusercontent.com/45260509/111474731-a2870300-872c-11eb-8748-6d7eefa39b30.jpg)

**Comment by FredVH** [comment]
I checked the txt-file and it contains the link, but the HTML page doesn't.

**Comment by lusassl-msft** [comment]
Yes you're right. At the moment we only show the link on the screen and not in the html report:

```
    if ($additionalDisplayValue -ne [string]::Empty) {
        $additionalDisplayValue += "`r`n`t`tMore Information: https://techcommunity.microsoft.com/t5/exchange-team-blog/exchange-server-and-smbv1/ba-p/1165615"

        $analyzedResults = Add-AnalyzedResultInformation -Details $additionalDisplayValue.Trim() `
            -DisplayGroupingKey $keySecuritySettings `
            -DisplayWriteType "Yellow" `
            -DisplayCustomTabNumber 2 `
            **-AddHtmlDetailRow $false `**
            -AnalyzedInformation $analyzedResults
    }
```

**Comment by FredVH** [comment]
Is there a reason why you're not showing the link in the html report, or is it just a mistake?

**Comment by lusassl-msft** [comment]
Normally (there are only a few checks that do, and I think they do because we took some checks over from v2 to v3) we do not provide the link to more information in the html report. Will discuss this inquiry internally and we'll then decide. 

@dpaulson45 let's add this to the backlog and decide during the new wiki work

**Comment by FredVH** [comment]
So you provide the possibilty to create an easy to read html-report, but the links to more information I have to dig up from a txt-file? How bizarre!

**Comment by FredVH** [comment]
I was going to submit a feature request to make the links in the html report clickable...

**Comment by Karl-WE** [comment]
@dpaulson45 if the state is SMB1 installed: True 
you might want to include a link to: https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3 for guidance (if not already included.

from your output you only reference why it should be disabled even when installed is already False.
Thank you for consideration.
