### ISSUE TITLE
DateTime format for non-us locales

### ISSUE THREAD

**Issue by MGOliver442** [dpaulson45/HealthChecker#566]
1st version of HealthChecker worked fine, new version (with date check) fails to run.
Our Exchange Server - Region is Australia
18/03/2021 dd/mm/yyyy

HealthChecker script returns: 
Exception calling "Parse" with "1" argument(s): "String was not recognized as a valid DateTime."
At C:\Users\administrator.ISRAEL\Downloads\HealthChecker2.ps1:547 char:9
+     if (([DateTime]::Parse($scriptBuildDate)).AddDays(10) -lt [DateTi ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FormatException

from the shell: date command returns this on this system
PS C:\Users\administrator.ISRAEL\Downloads> date

Thursday, 18 March 2021 4:13:00 PM

thanks
Marty

**Comment by lusassl-msft** [comment]
@MGOliver442 can you please drop us an email to **ExToolsFeedback[at]microsoft[dot]com**. I'll then send you a new version for validation.

**Comment by RedPeace** [comment]
Same problem here in germany.

Greetings
Gero

**Comment by lusassl-msft** [comment]
Thanks everyone for reporting this issue. I've checked in a PR to address it. Will be released soon. Track #567 .

**Comment by lusassl-msft** [comment]
Fixed with the latest release (3.3.7): https://aka.ms/ExHCDownload
