### ISSUE TITLE
[Check Request] Forest / Domain Functional Level / Exchange AD Schema Level

### ISSUE THREAD

**Issue by Karl-WE** [dpaulson45/HealthChecker#571]
**Is your request related to a problem? Please describe.**
Check the Active Directory Forest and Domain functional Level
Check the Active Directory Exchange Schema level

**Describe Check Request**
Your script does a great job to test Exchange infrastucture for best practices. 
It would be helpful to include FFL / DFL checks in compliance with the Exchange compat matrix
Please ask the author (blog.it-koehler.com) if you can incorporate his works or include checks

Checking the FFL / DFL also helps to compare with Exchange Compat Matrix (perferably use the en-us articles as the other languages happen to be outdated after changes)

I do not expect that your script can actually compare to the docs live, rather including try / catch for the Exchange Version and supported scenarios similar to your .net checks.

**Additional context**
https://blog.it-koehler.com/en/Archive/2313
https://docs.microsoft.com/en-us/exchange/plan-and-deploy/active-directory/ad-schema-changes?view=exchserver-2019
https://docs.microsoft.com/en-us/exchange/plan-and-deploy/active-directory/ad-schema-changes?view=exchserver-2016

To find the Domain Functional Level, use this command:
Get-ADDomain | fl Name,DomainMode

To find the Forest Functional Level, use this command:
Get-ADForest | fl Name,ForestMode

**Comment by dpaulson45** [comment]
What benefit does this provided? Worried about on tools boxes or Edge Servers where this might not apply. Don't know if we can even do a CU update anyways if the AD level is higher than what we support. The biggest thing would be that we have run into issues that i am aware of is the OS level on the DCs, not the domain or forest level.

**Comment by Karl-WE** [comment]
Hi @dpaulson45 it would make it easier to have all relevant data at one page that fits to the requirement of the Exchange compat matrix. 

Unfortunately it seem I have opened one PR for 2 seperate things. 

usecase:
1.  using this tool to prepare upgrade to a newer version (FFL / DFL)
2. a) Exchange Schema version,checking the Exchange schema level to understand if the next CU would need schema admin rights / schema changes.
2. b) check that the Schema level is correct according to the current CU level pre-patch
2. c) check that the Schema level is correct according to the current CU level post-patch

**Comment by Karl-WE** [comment]
ok thank you @dpaulson45 I am closing this. Thanks for your help and time.
