### ISSUE TITLE
[Work Item] Exchange Health Checker Console Output as HTML

### ISSUE THREAD

**Issue by Karl-WE** [dpaulson45/HealthChecker#572]
**Describe the work**
I would like to see an HTML output based on the console output. 
the console output uses colors to indicate good or improveable configurations. Text or XML output does not reflect this.

Perhaps this one can help you to create awesome HTML outputs. @PrzemyslawKlys uses it in his rojects like GPOZaurr.

**Additional Context**
https://github.com/EvotecIT/PSWriteHTML

**Comment by lusassl-msft** [comment]
@Karl-WE we already provide a way to generate an html output. Just run the script against every server you want to check.
After that, run the script as follows `.\HealthChecker.ps1 -BuildHtmlServersReport` to generate the html report.

**Comment by Karl-WE** [comment]
Thank you! Miss to check the switches. I will close this PR if you are satisfied with the HTML output or do you like to keep it open to check the PsWriteHTML module? @lusassl-msft
