### ISSUE TITLE
[Issue] Error: Mismatch in TLS version for client and server when RegKey "Enabled" set to Value "0xffffffff"

### ISSUE THREAD

**Issue by Sektorsync** [dpaulson45/HealthChecker#583]
Hello Team!

We get the following error from the HealthChecker Script regarding TLS Settings

================================================
Security Settings
-----------------
	LmCompatibilityLevel Settings: 5
		Description: Clients use only NTLMv2 authentication, and they use NTLMv2 session security if the server supports it. Domain controller refuses LM and NTLM authentication responses, but it accepts NTLMv2.
	TLS 1.0
		Server Enabled: False
		Server Disabled By Default: False
		Client Enabled: False
		Client Disabled By Default: True
	TLS 1.1
		Server Enabled: False
		Server Disabled By Default: False
		Client Enabled: False
		Client Disabled By Default: True
	TLS 1.2
		Server Enabled: False
		Server Disabled By Default: False
		Client Enabled: True
		Client Disabled By Default: False
			Error: Mismatch in TLS version for client and server. Exchange can be both client and a server. This can cause issues within Exchange for communication.
	SystemDefaultTlsVersions: True
	SystemDefaultTlsVersions - Wow6432Node: True
	SchUseStrongCrypto: False
	SchUseStrongCrypto - Wow6432Node: False
	SecurityProtocol: Tls12
		For More Information on how to properly set TLS follow these blog posts:
			Exchange Server TLS guidance Part 1: Getting Ready for TLS 1.2: https://techcommunity.microsoft.com/t5/Exchange-Team-Blog/Exchange-Server-TLS-guidance-part-1-Getting-Ready-for-TLS-1-2/ba-p/607649
			Exchange Server TLS guidance Part 2: Enabling TLS 1.2 and Identifying Clients Not Using It: https://techcommunity.microsoft.com/t5/Exchange-Team-Blog/Exchange-Server-TLS-guidance-Part-2-Enabling-TLS-1-2-and/ba-p/607761
			Exchange Server TLS guidance Part 3: Turning Off TLS 1.0/1.1: https://techcommunity.microsoft.com/t5/Exchange-Team-Blog/Exchange-Server-TLS-guidance-Part-3-Turning-Off-TLS-1-0-1-1/ba-p/607898
================================================

TLS 1.2 is akticvated fpr Client and Server, but we use the Value of

Enabled=0xffffffff

inated of

Enabled=1 

for the DWORD in

EXCHANGESERVER\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server\ 

But both values should have the same effect, right?

**Comment by lusassl-msft** [comment]
Hi @Sektorsync. The Health Checker project was moved to: https://aka.ms/ExchangeHealthChecker . Please use the latest version.
**You should use 0 or 1 instead of 0xffffffff** because this value can cause issues. Please see: https://github.com/dpaulson45/HealthChecker/issues/220
