### ISSUE TITLE
With Exchange 2013 CU21 apparently i'm unable the find the Exchange major version with the script

### ISSUE THREAD

**Issue by bartmgithub** [dpaulson45/HealthChecker#99]
I'm running the script using task scheduled from a management server. This has worked up till CU20 and version 2.26. After the customer upgraded to CU21 the script cannot determine the version and the loadbalancingreport fails mentioning it can only run for 2013 or higher.

**Comment by dpaulson45** [comment]
@bartmgithub please provide the -Verbose output and email the two output files to me and I will be able to take a look at this.

**Comment by dpaulson45** [comment]
@bartmgithub  please provide the output of your issue. There might actually be an issue within your environment. I don't believe there is an issue with the script as I have just retested Exchange 2013 CU21 on Windows Server 2012 R2. It works fine for normal running of the script as well as the load balancing report for v2.26 & v2.27.

**Comment by bartmgithub** [comment]
I am on site again on Monday to run the test. Anyway, I'll test with both. 26 and .27

Enjoy the weekend

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bartmgithub** [comment]
Sorry, Tuesday onsite, not Monday.

**Comment by bartmgithub** [comment]
Apparently it's caused by running the scripts from a management server. Anyway this used to work before CU21 so need to do some more research why this fails now.

Running the script directly in EMS on an Exchange server does work. I can get the major and minor versions from Exchange which I can't get from the remote machine.

Not sure yet why this started failing now.

From: Bart Meijer
Sent: Monday, November 19, 2018 12:13 PM
To: dpaulson45/HealthChecker <reply@reply.github.com>; dpaulson45/HealthChecker <HealthChecker@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [dpaulson45/HealthChecker] With Exchange 2013 CU21 apparently i'm unable the find the Exchange major version with the script (#99)

Sorry, Tuesday onsite, not Monday.

**Comment by bartmgithub** [comment]
Maybe related to this https://powershell.org/forums/topic/exchange-majorminor-versions-not-passed-remotely/

But still wondering why it used to work.

From: Bart Meijer
Sent: Tuesday, November 20, 2018 11:10 AM
To: dpaulson45/HealthChecker <reply@reply.github.com>; dpaulson45/HealthChecker <HealthChecker@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [dpaulson45/HealthChecker] With Exchange 2013 CU21 apparently i'm unable the find the Exchange major version with the script (#99)

Apparently it's caused by running the scripts from a management server. Anyway this used to work before CU21 so need to do some more research why this fails now.

Running the script directly in EMS on an Exchange server does work. I can get the major and minor versions from Exchange which I can't get from the remote machine.

Not sure yet why this started failing now.

From: Bart Meijer
Sent: Monday, November 19, 2018 12:13 PM
To: dpaulson45/HealthChecker <reply@reply.github.com>; dpaulson45/HealthChecker <HealthChecker@noreply.github.com<mailto:HealthChecker@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [dpaulson45/HealthChecker] With Exchange 2013 CU21 apparently i'm unable the find the Exchange major version with the script (#99)

Sorry, Tuesday onsite, not Monday.

**Comment by bartmgithub** [comment]
Management machine was not yet upgraded to CU21. That's being planned now. Might be the cause.

From: Bart Meijer
Sent: Tuesday, November 20, 2018 11:17 AM
To: 'dpaulson45/HealthChecker' <reply@reply.github.com>; 'dpaulson45/HealthChecker' <HealthChecker@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [dpaulson45/HealthChecker] With Exchange 2013 CU21 apparently i'm unable the find the Exchange major version with the script (#99)

Maybe related to this https://powershell.org/forums/topic/exchange-majorminor-versions-not-passed-remotely/

But still wondering why it used to work.

From: Bart Meijer
Sent: Tuesday, November 20, 2018 11:10 AM
To: dpaulson45/HealthChecker <reply@reply.github.com>; dpaulson45/HealthChecker <HealthChecker@noreply.github.com<mailto:HealthChecker@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [dpaulson45/HealthChecker] With Exchange 2013 CU21 apparently i'm unable the find the Exchange major version with the script (#99)

Apparently it's caused by running the scripts from a management server. Anyway this used to work before CU21 so need to do some more research why this fails now.

Running the script directly in EMS on an Exchange server does work. I can get the major and minor versions from Exchange which I can't get from the remote machine.

Not sure yet why this started failing now.

From: Bart Meijer
Sent: Monday, November 19, 2018 12:13 PM
To: dpaulson45/HealthChecker <reply@reply.github.com>; dpaulson45/HealthChecker <HealthChecker@noreply.github.com<mailto:HealthChecker@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [dpaulson45/HealthChecker] With Exchange 2013 CU21 apparently i'm unable the find the Exchange major version with the script (#99)

Sorry, Tuesday onsite, not Monday.

**Comment by bartmgithub** [comment]
Yes, fixed with the CU upgrade on the management machine. Apologies for the report 😊

From: Bart Meijer
Sent: Tuesday, November 20, 2018 2:51 PM
To: 'dpaulson45/HealthChecker' <reply@reply.github.com>; 'dpaulson45/HealthChecker' <HealthChecker@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [dpaulson45/HealthChecker] With Exchange 2013 CU21 apparently i'm unable the find the Exchange major version with the script (#99)

Management machine was not yet upgraded to CU21. That’s being planned now. Might be the cause.

From: Bart Meijer
Sent: Tuesday, November 20, 2018 11:17 AM
To: 'dpaulson45/HealthChecker' <reply@reply.github.com>; 'dpaulson45/HealthChecker' <HealthChecker@noreply.github.com<mailto:HealthChecker@noreply.github.com>>
Cc: 'Mention' <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [dpaulson45/HealthChecker] With Exchange 2013 CU21 apparently i'm unable the find the Exchange major version with the script (#99)

Maybe related to this https://powershell.org/forums/topic/exchange-majorminor-versions-not-passed-remotely/

But still wondering why it used to work.

From: Bart Meijer
Sent: Tuesday, November 20, 2018 11:10 AM
To: dpaulson45/HealthChecker <reply@reply.github.com>; dpaulson45/HealthChecker <HealthChecker@noreply.github.com<mailto:HealthChecker@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [dpaulson45/HealthChecker] With Exchange 2013 CU21 apparently i'm unable the find the Exchange major version with the script (#99)

Apparently it’s caused by running the scripts from a management server. Anyway this used to work before CU21 so need to do some more research why this fails now.

Running the script directly in EMS on an Exchange server does work. I can get the major and minor versions from Exchange which I can’t get from the remote machine.

Not sure yet why this started failing now.

From: Bart Meijer
Sent: Monday, November 19, 2018 12:13 PM
To: dpaulson45/HealthChecker <reply@reply.github.com>; dpaulson45/HealthChecker <HealthChecker@noreply.github.com<mailto:HealthChecker@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [dpaulson45/HealthChecker] With Exchange 2013 CU21 apparently i'm unable the find the Exchange major version with the script (#99)

Sorry, Tuesday onsite, not Monday.

**Comment by dpaulson45** [comment]
Thanks for the update. Closing out the issue.
